# Generated by Django 5.1.6 on 2026-02-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="category",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="gst_number",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="pan_number",
        ),
        migrations.AlterField(
            model_name="vendor",
            name="contact",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[("approved", "Approved"), ("rejected", "Rejected")],
                default="approved",
                max_length=10,
            ),
        ),
    ]
