# Generated by Django 5.1.6 on 2026-02-28 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfp", "0002_remove_vendor_category_remove_vendor_gst_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="vendors", to="rfp.category"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="employees",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vendor",
            name="gst_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="vendor",
            name="pan_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="vendor",
            name="revenue",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
