# Generated by Django 5.1.6 on 2026-02-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rfp", "0003_vendor_categories_vendor_employees_vendor_gst_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="employees",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="gst_number",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="pan_number",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="revenue",
        ),
    ]
