# Generated by Django 5.1.6 on 2026-02-28 11:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfp", "0004_remove_vendor_categories_remove_vendor_employees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendors",
                to="rfp.category",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="employees_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="gst_no",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="pan_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="revenue_last_3_years_lakhs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
